### ISSUE TITLE
Running just matlab fails

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1012]
Running fitbenchmarking on the NIST average difficultly test set with the ini file:
```
[FITTING]
software: matlab
```
fails on the `fitbenchmarking-medium` VM.  We get the output:
```
dgk98065@fitbenchmarking-medium:~/fitbenchmarking$ fitbenchmarking -o examples/all_softwares.ini -p examples/benchmark_problems/NIST/average_difficulty/ -r fb-results-$(date +"%d-%m-%y") -d
Running the benchmarking on the NIST_average_difficulty problem set
Parsing problems
Running problems

#################################
 Running data from: ENSO.dat 1/9
#################################
    Starting value: 1/2
        Software: MATLAB
Unknown exception. Exiting.
Traceback (most recent call last):
  File "/home/dgk98065/venv/lib/python3.8/site-packages/matlab/engine/__init__.py", line 45, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matlabengineforpython3_8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dgk98065/venv/lib/python3.8/site-packages/matlab/engine/__init__.py", line 64, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/dgk98065/Matlab/R2021a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libssl.so.1.1: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dgk98065/venv/bin/fitbenchmarking", line 8, in <module>
    sys.exit(main())
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/cli/main.py", line 313, in main
    run(problem_sets=args.problem_sets,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/cli/exception_handler.py", line 29, in wrapped
    return f(*args, **kwargs)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/cli/main.py", line 239, in run
    benchmark(options=options,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 71, in benchmark
    loop_over_benchmark_problems(problem_group, options)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 137, in loop_over_benchmark_problems
    loop_over_starting_values(
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 179, in loop_over_starting_values
    loop_over_cost_function(problem=problem,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 229, in loop_over_cost_function
    loop_over_fitting_software(cost_func=cost_func,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 275, in loop_over_fitting_software
    controller_cls = ControllerFactory.create_controller(
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/controllers/controller_factory.py", line 39, in create_controller
    module = import_module('.' + module_name, __package__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/controllers/matlab_controller.py", line 5, in <module>
    import matlab.engine
  File "/home/dgk98065/venv/lib/python3.8/site-packages/matlab/engine/__init__.py", line 66, in <module>
    raise EnvironmentError('Please reinstall MATLAB Engine for Python or contact '
OSError: Please reinstall MATLAB Engine for Python or contact MathWorks Technical Support for assistance: /home/dgk98065/Matlab/R2021a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libssl.so.1.1: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0

```
Running the matlab engine in a separate python session works, as does running Matlab minimizers in Fitbenchmarking when another minimizer is called first.

Note that this behaviour can't be replicated on another machine.

**Comment by jfowkes** [comment]
Works perfectly for me on Mac. @tyronerees as the trace suggests you should probably try reinstalling your matlab python engine, in your shell:
```bash
$ cd matlabroot/extern/engines/python
$ rm -rf build
$ python3 setup.py install
```
Note that this needs to be the same venv python that you use with fitbechmarking or your venv needs to have access to the system packages (if you used the `--system-site-packages` flag when setting it up). Also here matlabroot is given by running the `matlabroot` command in matlab.

**Comment by tyronerees** [comment]
Just tried reinstalling this again, and still get the same behaviour.  No issues were raised at all at build time for the matlab engine.  And very strange that it works perfectly if another package is selected first.

I tried using the system python in the build step, rather than the venv python, just as a sanity check, but this (as expected) causes Matlab to fail everywhere.  

Very strange that it works perfectly if another package is selected first.  Since this works on other machines, I suspect it's an issue with the particular setup here, but I have no idea which part of it is the issue.

**Comment by jfowkes** [comment]
Very strange, especially that it works for @AndrewLister-STFC under presumably a very similar VM on windows.

**Comment by tyronerees** [comment]
I can no longer reproduce this on fitbenchmarking-medium, so I assume this has now been fixed (either on the setup on fitbenchmarking-medium, or with the changes to the matlab workings). Closing the issue.
