### ISSUE TITLE
Max runtime error?

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#1025]
When running `1D_core_shell_parallelepiped_neutron_def0` using `bumps ameoba`, the computation hung with no progress.  Re-running using top showed that 100% of the CPU was being used until the max runtime set in the calling script was hit, and then no progress was made for several minutes.  Pressing `Ctrl-C` to get the terminal back gave the following trace:

```
dgk98065@fitbenchmarking-medium:~/fitbenchmarking$ ^CTraceback (most recent call last):
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/fitproblem.py", line 496, in _nllf_components
    pmodel = (self.model_nllf()
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/fitproblem.py", line 288, in model_nllf
    return self.fitness.nllf()
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/curve.py", line 280, in nllf
    r = self.residuals()
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/curve.py", line 277, in residuals
    return (self.theory() - self.y) / self.dy
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/curve.py", line 252, in theory
    self._cached_theory = self._compute_theory(self.x)
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/curve.py", line 258, in _compute_theory
    return self._function(x, **kw)
  File "<string>", line 2, in fitFunction
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/parsing/fitting_problem.py", line 140, in eval_model
    self.timer.check_elapsed_time()
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/utils/timer.py", line 61, in check_elapsed_time
    raise MaxRuntimeError
fitbenchmarking.utils.exceptions.MaxRuntimeError: Minimizer runtime exceeded maximum runtime

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dgk98065/venv/bin/fitbenchmarking", line 8, in <module>
    sys.exit(main())
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/cli/main.py", line 316, in main
    run(problem_sets=args.problem_sets,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/cli/exception_handler.py", line 29, in wrapped
    return f(*args, **kwargs)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/cli/main.py", line 242, in run
    benchmark(options=options,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 70, in benchmark
    loop_over_benchmark_problems(problem_group, options)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 131, in loop_over_benchmark_problems
    loop_over_starting_values(
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 170, in loop_over_starting_values
    loop_over_cost_function(problem=problem,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 218, in loop_over_cost_function
    loop_over_fitting_software(cost_func=cost_func,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 271, in loop_over_fitting_software
    loop_over_minimizers(controller=controller,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 352, in loop_over_minimizers
    results = loop_over_jacobians(controller, options, grabbed_output)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 400, in loop_over_jacobians
    new_result = loop_over_hessians(controller,
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 463, in loop_over_hessians
    chi_sq, runtime = perform_fit(controller, options, grabbed_output)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/core/fitting_benchmarking.py", line 526, in perform_fit
    runtime_list = timeit.Timer(
  File "/usr/lib/python3.8/timeit.py", line 205, in repeat
    t = self.timeit(number)
  File "/usr/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/controllers/base_controller.py", line 213, in execute
    self.fit()
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/controllers/bumps_controller.py", line 128, in fit
    result = bumpsFit(self._fit_problem, method=self.minimizer)
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/fitters.py", line 1264, in fit
    x, fx = driver.fit()
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/fitters.py", line 969, in fit
    x, fx = fitter.solve(monitors=self.monitors,
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/fitters.py", line 511, in solve
    result = simplex(f=self.problem.nllf, x0=self.problem.getp(),
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/simplex.py", line 259, in simplex
    fxcc = func(xcc)
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/simplex.py", line 35, in function_wrapper
    return function(x)
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/fitproblem.py", line 474, in nllf
    pparameter, pconstraints, pmodel = self._nllf_components()
  File "/home/dgk98065/venv/lib/python3.8/site-packages/bumps/fitproblem.py", line 504, in _nllf_components
    logging.error("\n".join(info))
  File "/usr/lib/python3.8/logging/__init__.py", line 2049, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
KeyboardInterrupt
```

**Comment by AndrewLister-STFC** [comment]
It looks like we can pass `abort_test` to the call to fit in bumps. This should be a function that takes no arguments and returns a boolean that is checked to see if the computation should continue.
This should probably just return something like `time.now() < start+max_runtime` for our purposes. I'll put in a PR this afternoon.
