### ISSUE TITLE
Bayes bugs

### ISSUE THREAD

**Issue by AnthonyLim23** [fitbenchmarking/fitbenchmarking#1248]
From https://github.com/fitbenchmarking/fitbenchmarking/pull/1236

There are multiple bugs when using Bayesian methods.

I got this error
```
  File "\\?\C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\Scripts\fitbenchmarking-script.py", line 33, in <module>
    sys.exit(load_entry_point('FitBenchmarking', 'console_scripts', 'fitbenchmarking')())
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\main.py", line 432, in main
    run(problem_sets=args.problem_sets,
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\exception_handler.py", line 29, in wrapped
    return f(*args, **kwargs)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\main.py", line 326, in run
    save_results(group_name=label,
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\utils\write_files.py", line 29, in wrapper
    return function(*args, **kwargs)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\core\results_output.py", line 76, in save_results
    create_plots(options, results_dict, best_results, fig_dir)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\core\results_output.py", line 661, in create_plots
    plot_path = plot.plot_posteriors(result)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\results_processing\plots.py", line 203, in plot_posteriors
    scipy_fit = result.params_pdfs['scipy_pfit']
KeyError: 'scipy_pfit'
```
when running the NIST/high_difficulty

running the Muon examples gives this error
```
File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```

the crystal field examples give a key error
```
Traceback (most recent call last):
  File "\\?\C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\Scripts\fitbenchmarking-script.py", line 33, in <module>
    sys.exit(load_entry_point('FitBenchmarking', 'console_scripts', 'fitbenchmarking')())
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\main.py", line 432, in main
    run(problem_sets=args.problem_sets,
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\exception_handler.py", line 29, in wrapped
    return f(*args, **kwargs)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\main.py", line 326, in run
    save_results(group_name=label,
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\utils\write_files.py", line 29, in wrapper
    return function(*args, **kwargs)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\core\results_output.py", line 76, in save_results
    create_plots(options, results_dict, best_results, fig_dir)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\core\results_output.py", line 661, in create_plots
    plot_path = plot.plot_posteriors(result)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\results_processing\plots.py", line 207, in plot_posteriors
    fig.append_trace(go.Histogram(x=result.params_pdfs[name],
KeyError: 'f0.FWHM'
```

MultiFit just throws an error
```
Traceback (most recent call last):
  File "\\?\C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\Scripts\fitbenchmarking-script.py", line 33, in <module>
    sys.exit(load_entry_point('FitBenchmarking', 'console_scripts', 'fitbenchmarking')())
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\main.py", line 432, in main
    run(problem_sets=args.problem_sets,
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\exception_handler.py", line 29, in wrapped
    return f(*args, **kwargs)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\cli\main.py", line 326, in run
    save_results(group_name=label,
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\utils\write_files.py", line 29, in wrapper
    return function(*args, **kwargs)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\core\results_output.py", line 76, in save_results
    create_plots(options, results_dict, best_results, fig_dir)
  File "c:\users\btr75544\work\fitbenchmarking\fitbenchmarking\core\results_output.py", line 594, in create_plots
    tmp_df = pd.DataFrame({'x': cat_results[0].data_x,
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\site-packages\pandas\core\frame.py", line 664, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\site-packages\pandas\core\internals\construction.py", line 493, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\site-packages\pandas\core\internals\construction.py", line 118, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Users\btr75544\AppData\Local\mambaforge\envs\fitbenchmarking\lib\site-packages\pandas\core\internals\construction.py", line 666, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same leng
```

**Comment by jess-farmer** [comment]
The first error `KeyError: 'scipy_pfit'` occurs when the MCMC fit has been successful, but the scipy fit (used to calculate confidence values for MCMC fits) has been unsuccessful. This behaviour should be changed so that the user is given a warning to say that the scipy fit was unsuccessful, and confidence values for that minimizer are not calculated. Users should also be able to choose which minimizer is used for calculating confidence values - this should be added to the Fitbenchmarking options.
