### ISSUE TITLE
Bug when using SciPy v0.17.0

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#128]
Change software='mantid' to software='scipy' in example_runScripts.py gives the following output when using SciPy v0.17.0

Resolution: either document the required version of SciPy, or find a workaround.

python new_runScripts.py FrameworkManager-[Notice] Welcome to Mantid 3.13.0
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid3.13
DllOpen-[Error] Could not open library /opt/Mantid/plugins/libMantidVatesAlgorithms.so: libvtkIOLegacy-pv5.4.so.1: cannot open shared object file: No such file or directory
DllOpen-[Error] Could not open library /opt/Mantid/plugins/libMantidVatesAlgorithms.so: libvtkIOLegacy-pv5.4.so.1: cannot open shared object file: No such file or directory
DownloadInstrument-[Notice] All instrument definitions up to date
Load-[Notice] Load started
Load-[Notice] Load successful, Duration 0.09 seconds
Traceback (most recent call last):
  File "new_runScripts.py", line 76, in <module>
    use_errors=use_errors, results_dir=results_dir)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting_benchmarking.py", line 62, in do_fitting_benchmark
    for block in problem_groups[group_name]]
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting_benchmarking.py", line 88, in do_fitting_benchmark_group
    results_dir)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitbenchmark_one_problem.py", line 72, in fitbm_one_problem
    minimizers, cost_function)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitbenchmark_one_problem.py", line 107, in fit_one_function_def
    cost_function)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting/scipyfit.py", line 58, in benchmark
    fit(data, function, minimizer, cost_function, init_function_def)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting/scipyfit.py", line 91, in fit
    minimizer, cost_function)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting/scipyfit.py", line 146, in execute_fit
    p0=initial_params, method=minimizer, maxfev=500)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/minpack.py", line 658, in curve_fit
    **kwargs)
TypeError: least_squares() got an unexpected keyword argument 'maxfev'

**Comment by Anders-Markvardsen** [comment]
From meeting with Tyrone today. This problem occurs when installing mantid-developer which includes an older version of scipy. 

Updated resolution: add documentation to warn users who build mantid from source about this

**Comment by bb511** [comment]
@Anders-Markvardsen 
Should I add a warning for this on the following pages?
https://github.com/mantidproject/fitbenchmarking/wiki/Installing-Mantid
https://github.com/mantidproject/fitbenchmarking/edit/master/README.md

If it is only an issue with the developer version, then I think the users who install mantid through FitBenchmarking should be fine, so no warning should be added to the installation scripts.

**Comment by Anders-Markvardsen** [comment]
I agree with the above - thanks

**Comment by tyronerees** [comment]
I'm getting this issue again with our current `setup.py`, following the instructions in the readme, even when not calling Mantid.  

@Anders-Markvardsen / @AnthonyLim23 -- any objections to just requiring Scipy >= 0.18?  v 0.18 and above works fine for me

**Comment by AndrewLister-STFC** [comment]
This was fixed with #226
