### ISSUE TITLE
Fitbenchmarking fails with Mantid when no weights are used

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#245]
**Description of the error**
Setting `use_errors = False` in `example_runScripts.py` causes the example script to fail if `software = ['mantid']`.

**Describe the expected result**
FitBenchmarking should run successfully on an unweighted problem.

**Describe the actual result**
We get 
```
dgk98065@cmg-mantid:~/fitbenchmarking$ python example_scripts/example_runScripts.py 

Running the benchmarking on the NIST_low_difficulty problem set

/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py:519: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
[15:11:41]  WARNING main.py: Fit failed: Optimal parameters not found: Number of calls to function has reached maxfev = 500.
FrameworkManager-[Notice] Welcome to Mantid 4.1.0
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid4.1
DownloadInstrument-[Notice] All instrument definitions up to date
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.03 seconds
ConvertToPointData-[Notice] ConvertToPointData started
ConvertToPointData-[Notice] ConvertToPointData successful, Duration 0.00 seconds
Fit-[Notice] Fit started
Fit-[Notice] Fit status: success
Fit-[Notice] Stopped after 7 iterations
Fit-[Notice] Fit successful, Duration 0.05 seconds
ConvertToPointData-[Notice] ConvertToPointData started
ConvertToPointData-[Notice] ConvertToPointData successful, Duration 0.00 seconds
Fit-[Notice] Fit started
Fit-[Notice] Fit status: success
Fit-[Notice] Stopped after 33 iterations
Fit-[Notice] Fit successful, Duration 0.07 seconds
Traceback (most recent call last):
  File "example_scripts/example_runScripts.py", line 99, in <module>
    use_errors=use_errors, results_dir=results_dir)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting_benchmarking.py", line 48, in do_fitting_benchmark
    prob_results = do_benchmarking(user_input, problem_group, group_name)
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting_benchmarking.py", line 74, in do_benchmarking
    list_prob_results.append(do_fitbm_group(user, block))
  File "/home/dgk98065/fitbenchmarking/fitbenchmarking/fitting_benchmarking.py", line 100, in do_fitbm_group
    results_prob = fitbm_one_prob(user_input, problem)
  File "/home/dgk98065/.local/lib/python2.7/site-packages/FitBenchmarking-0.1.dev2-py2.7.egg/fitbenchmarking/fitbenchmark_one_problem.py", line 48, in fitbm_one_prob
    user_input.group_results_dir)
  File "/home/dgk98065/.local/lib/python2.7/site-packages/FitBenchmarking-0.1.dev2-py2.7.egg/fitbenchmarking/fitting/plotting/plots.py", line 34, in make_plots
    raw_data = get_data_points(problem)
  File "/home/dgk98065/.local/lib/python2.7/site-packages/FitBenchmarking-0.1.dev2-py2.7.egg/fitbenchmarking/fitting/plotting/plots.py", line 55, in get_data_points
    raw_data = data("Data", xData, yData, eData)
  File "/home/dgk98065/.local/lib/python2.7/site-packages/FitBenchmarking-0.1.dev2-py2.7.egg/fitbenchmarking/fitting/plotting/plot_helper.py", line 37, in __init__
    if(len(E) == 0):
TypeError: object of type 'NoneType' has no len()
```

**Comment by tyronerees** [comment]
Issue #247 needs to be fixed before this is addressed
