### ISSUE TITLE
Sasview outputs

### ISSUE THREAD

**Issue by tyronerees** [fitbenchmarking/fitbenchmarking#276]
**Description of the error**
When Mantid problems are send to bumps, a solution is obtained (hence #206 has been closed), but many errors are reported.

**Describe the expected result**
No errors should be reported.

**Describe the actual result**
We get multiple outputs like:
```
[09:43:02]  ERROR fitproblem.py: Traceback (most recent call last):
  File "/home/dgk98065/.local/lib/python2.7/site-packages/bumps/fitproblem.py", line 477, in _nllf_components
    if pparameter + pconstraints <= self.soft_limit
  File "/home/dgk98065/.local/lib/python2.7/site-packages/bumps/fitproblem.py", line 276, in model_nllf
    return self.fitness.nllf()
  File "/home/dgk98065/.local/lib/python2.7/site-packages/bumps/curve.py", line 183, in nllf
    r = self.residuals()
  File "/home/dgk98065/.local/lib/python2.7/site-packages/bumps/curve.py", line 180, in residuals
    return (self.theory() - self.y) / self.dy
  File "/home/dgk98065/.local/lib/python2.7/site-packages/bumps/curve.py", line 165, in theory
    self._cached_theory = self._function(x, **kw)
  File "<string>", line 2, in fitFunction
  File "/opt/Mantid/bin/mantid/fitfunctions.py", line 176, in __call__
    self.fun.setParameter(i, params[i])
ValueError: Trying to set an infinity value (-inf) to parameter A0

                                   f0_A0 *invalid*        -inf in (-inf,inf)
                                   f0_A1 *invalid*         inf in (-inf,inf)
                                    f1_A *invalid*         inf in (-inf,inf)
                                    f1_B *invalid*        -inf in (-inf,inf)
                                    f1_I *invalid*        -inf in (-inf,inf)
                                    f1_S *invalid*        -inf in (-inf,inf)
                                   f1_X0 *invalid*        -inf in (-inf,inf)
```

The fact that the right answer is obtained suggests this is a cosmetic issue, but this needs investigating.

**Comment by AndrewLister-STFC** [comment]
This is just for the pt minimizer: https://bumps.readthedocs.io/en/latest/guide/optimizer.html#fit-pt

Note: It is marked as experimental, perhaps we should just remove it.

**Comment by wathen** [comment]
Checked and no other bumps minimizers produce these errors
